// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: demo_orders.sql

package sqlc

import (
	"context"
)

const confirmDemoOrder = `-- name: ConfirmDemoOrder :execrows
UPDATE demo_orders SET status = 'paid' WHERE id = $1 AND status = 'pending'
`

func (q *Queries) ConfirmDemoOrder(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, confirmDemoOrder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDemoInventory = `-- name: CreateDemoInventory :exec
INSERT INTO demo_inventory (id, available) VALUES ($1, $2)
`

type CreateDemoInventoryParams struct {
	ID        string `json:"id"`
	Available int32  `json:"available"`
}

func (q *Queries) CreateDemoInventory(ctx context.Context, arg CreateDemoInventoryParams) error {
	_, err := q.db.Exec(ctx, createDemoInventory, arg.ID, arg.Available)
	return err
}

const createDemoOrder = `-- name: CreateDemoOrder :exec
INSERT INTO demo_orders (id, inventory_id, quantity, total_cents)
VALUES ($1, $2, $3, $4)
`

type CreateDemoOrderParams struct {
	ID          string `json:"id"`
	InventoryID string `json:"inventory_id"`
	Quantity    int32  `json:"quantity"`
	TotalCents  int32  `json:"total_cents"`
}

func (q *Queries) CreateDemoOrder(ctx context.Context, arg CreateDemoOrderParams) error {
	_, err := q.db.Exec(ctx, createDemoOrder,
		arg.ID,
		arg.InventoryID,
		arg.Quantity,
		arg.TotalCents,
	)
	return err
}

const getDemoOrder = `-- name: GetDemoOrder :one
SELECT id, inventory_id, quantity, total_cents, status FROM demo_orders WHERE id = $1
`

func (q *Queries) GetDemoOrder(ctx context.Context, id string) (DemoOrder, error) {
	row := q.db.QueryRow(ctx, getDemoOrder, id)
	var i DemoOrder
	err := row.Scan(
		&i.ID,
		&i.InventoryID,
		&i.Quantity,
		&i.TotalCents,
		&i.Status,
	)
	return i, err
}

const reserveDemoInventory = `-- name: ReserveDemoInventory :one
UPDATE demo_inventory SET available = available - $1::integer
WHERE id = $2 AND available >= $1::integer
RETURNING available
`

type ReserveDemoInventoryParams struct {
	Quantity int32  `json:"quantity"`
	ID       string `json:"id"`
}

func (q *Queries) ReserveDemoInventory(ctx context.Context, arg ReserveDemoInventoryParams) (int32, error) {
	row := q.db.QueryRow(ctx, reserveDemoInventory, arg.Quantity, arg.ID)
	var available int32
	err := row.Scan(&available)
	return available, err
}
