// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type DemoInventory struct {
	ID        string `json:"id"`
	Available int32  `json:"available"`
}

type DemoOrder struct {
	ID          string `json:"id"`
	InventoryID string `json:"inventory_id"`
	Quantity    int32  `json:"quantity"`
	TotalCents  int32  `json:"total_cents"`
	Status      string `json:"status"`
}

type Task struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Completed bool      `json:"completed"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
