// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package sqlc

import (
	"context"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, title)
VALUES ($1, $2)
RETURNING id, title, completed, created_at, updated_at
`

type CreateTaskParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.ID, arg.Title)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, completed, created_at, updated_at
FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskCompleted = `-- name: UpdateTaskCompleted :one
UPDATE tasks
SET completed = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, completed, created_at, updated_at
`

type UpdateTaskCompletedParams struct {
	ID        string `json:"id"`
	Completed bool   `json:"completed"`
}

func (q *Queries) UpdateTaskCompleted(ctx context.Context, arg UpdateTaskCompletedParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskCompleted, arg.ID, arg.Completed)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
